### ISSUE TITLE
teleport infinito al entrar a la carcel

### ISSUE THREAD

**Issue by x4sTaTic** [ao-oficial/ao-cliente#9]
Cuando te quedas parado en un tile con pena de carcel no dura practicamente nada en enviarte en cana y queda teletransportandote infinitamente al exterior y queda muerto el personaje ahi clavado como un campeón, sin poder volver a utilizar el personaje y  no queda otra que crearte otro nuevo.
Aunque salgas y vuelvas a logear queda igual

**Comment by cucsijuan** [comment]
Duplicate of ao-oficial/ao-server#1
